FROM tensorflow/tensorflow:2.15.0

RUN pip install --upgrade pip
RUN pip install onnx==1.15.0 \
    onnx-tf==1.10.0 \
    ml-dtypes==0.2.0 \
    protobuf==4.23.4 \
    tensorflow-probability==0.23.0 \
    keras==2.15.0 \
    tensorflow-addons==0.23.0 \
    tf-keras